### ISSUE TITLE
Map has all white overlay until moved with mouse curso

### ISSUE THREAD

**Issue by RaspberrySpi** [mrdis/MMM-google-route#10]
Hello,

Firstly thanks for sharing your module.  

I have an issue when I am trying to display more than one route on a page.  Both maps load, but have an all white overlay that only goes away if I interact with the map with mouse.  I can usually see the outline of the route through the white overlay but no details.
---------------------------
        {
            module: 'MMM-google-route',
            position: 'top_left',
            pages: {"Skiing" : "bottom_left"},
            config: {
                key: 'KEY',
                title: "To Hoch-y-Brig",
                height: '200px',
                width: '600px',
                refreshPeriod: '15',
                directionsRequest:{
                    origin: '46.7713684,9.5334896',
                    destination: '47.0200755,8.8066734'
                }
            }
        },
------------------------

Thanks!

**Comment by mrdis** [comment]
Your configuration works fine if I try it, may this be due to other modules you are using?
What is that "pages" field? it doesn't seem like a default configuration field..

**Comment by RaspberrySpi** [comment]
Thanks mrdis you were right.  The pages config refers to the https://github.com/edward-shen/MMM-pages module and when that's also active, with >1 instance on the page I end up with the white overlay.  Thank you for solving the mystery!  Cheers.

**Comment by mrdis** [comment]
Ok, I suppose we can close this then.
