### ISSUE TITLE
Add functionality like offHours

### ISSUE THREAD

**Issue by mlehtmets** [mrdis/MMM-google-route#12]
Hello!
I'm not really good at programming, but would like to add to this module some extra funtionality like MMM-Traffic.js has.
4 extra configuration modes.
So that it wouldnt request the API all the time, but only the times when we but into defaults like from 7 in the morning until 9 in the morning.
showWeekend - boolean
allTime: boolean
startHr: 7
endHr: 9
I tried to add it to the .js, but seems that I'm missing something.

**Comment by mrdis** [comment]
Hi, I just pushed this functionality, check out [the readme](https://github.com/mrdis/MMM-google-route#using-mmm-modulescheduler-to-configure-the-route-refresh-interval)
