### ISSUE TITLE
Disable map

### ISSUE THREAD

**Issue by julien-bouquet** [mrdis/MMM-google-route#13]
Hello, 

I do a Pull Request to manage, if we want to show or hide map. 
By default, this map is show, but if we want to hide it, we can with a param

**Comment by mrdis** [comment]
Thanks Julien, I'll take a look at it.
Anyway, if you would like to hide the map, have you considered using the [MyCommute](https://github.com/jclarke0000/MMM-MyCommute) module instead? 
It shows you the routes without showing the map.

**Comment by julien-bouquet** [comment]
Thanks you, 

I haven't seen this module.So, I will take this module probably.

**Comment by mrdis** [comment]
Closing as this seems to be solved
