### ISSUE TITLE
Help With Cron Scheduling

### ISSUE THREAD

**Issue by dxfan227** [mrdis/MMM-google-route#16]
I want to run my api commands every 5 min from 6 am-11am. and then once every hour all other times. soooooo I need to use the scheduler module? do I have to hide the google-route module during those times for it not to call api's? or what?

this is the cron date I have come up with 5,10,15,20,25,30,35,40,50,55 6-11 * * *

also to get the every hour all other times do I just set that part in the regular config interval?

**Comment by mrdis** [comment]
Yes, you just set the refreshPeriod parameter to 60, to trigger a refresh every hour, and then use the scheduler module with the cron expression above for the additional refresh triggers.
Just notice that with that cron expression refresh will be triggered also at 11:05,11:10,...,11:55. You should use 6-10 instead of 6-11 to have the last scheduled refresh at 10:55.
It's not necessary to hide the module, it should call the API only when refreshed.

**Comment by dxfan227** [comment]
Beautiful. Thank you for the quick reply and wonderful module. I started last week with zero code experience , zero Linux experience, and zero hardware experience. And I now have a working magic mirror on my raspberry pi with a salvaged lcd from a lap top!

3 more questions.

1 Is there any way to check and ensure the schedule is performing as expected?

2 I have tried to fool around with the google maps api stuff, I want to get a traffic layer over my route but the best I can do is over the entire map.

3. Google maps gives two routes to me.... the first is with a toll road..... the second is with a small side street and then that toll road. The alternative I would like to have is with a different free way vs the toll road. I couldn’t seem to get that to happen. The best I could do was set a way point.... this forced the map to route on the different free way but of course doesn’t list the toll road option any longer... is there any way to force way point for ONLY the alternative route?

**Comment by mrdis** [comment]
I just updated the code to show how long ago the route was refreshed, so you can use that information to check if the schedule is performing well, I guess. You need to update the module, though.

Regarding the traffic, it doesn't seem to be possible to have an overlay for the route only, unfortunately.

And regarding the alternative routes, there are no configuration options either. 
Maybe you can use another instance of the module, and set the avoidTolls directions option. It would occupy some more space on the mirror, but you would have both routes showing up.

**Comment by dxfan227** [comment]
Thank you, how does one update the module? Sorry I'm very new at this all. And would I expect to lose any "custom" code I have added to any files within the module.

**Comment by mrdis** [comment]
Basically you should open a shell in the module folder and execute 'git pull'.
But if you changed the code then it gets a bit more complicated, and you should understand the basics of working with git. 
[Here](http://rogerdudler.github.io/git-guide/) is a brief getting started guide on using git.

**Comment by dxfan227** [comment]
thanks, ill take a look tonight. I'll double check to make sure I didnt make any "hard" changes to your code.
