### ISSUE TITLE
Does this module have the capability of refreshing upon notification?

### ISSUE THREAD

**Issue by dxfan227** [mrdis/MMM-google-route#18]
Love this module!

Currently have it refreshing according to a custom cron job. but was wondering if I could refine it further. I have mmm.motion detector installed so the monitor turns off and on with motion. I was wondering if there was a way to send a notification from mmm-motion detector that would tell google-route to refresh when it sees motion. Just another effort to keep the api calls down.

**Comment by mrdis** [comment]
Hey, thanks for your appreciation!
I just pushed this feature, you just need to add the notification id to the `listen` configuration param.

**Comment by dxfan227** [comment]
Cool. So theoretically is it possible to have this module not make any api requests .... and then set the listen param to coincide with motion detection.... that way every time someone get in front of the mirror that’s when it makes an api call?

**Comment by mrdis** [comment]
Sure! Just set the `refreshPeriod` param to 0 and there won't be any periodic requests.
