### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by dxfan227** [mrdis/MMM-google-route#19]
Hi!

Love the module, I notice that after about a day or so I get " Google Unknown_Errow" Where the estimated route time and distance should be. The map still is loaded fine. Is there any way to pin down the issue? I assume it's some kind of wifi sleep mode I might be entering? not really sure....

**Comment by mrdis** [comment]
Hi, I may be a little bit late :) 
Are you still having this issue?

**Comment by dxfan227** [comment]
I am not sure as I have had the device unplugged for a few months while I save up funds to finish the project. I’ll let you know though once things are back up and running.

**Comment by mrdis** [comment]
I'm closing this since it seems to be ok

**Comment by Gara64** [comment]
For the record, I occasionally had an `UNKNOWN ERROR`, which appeared to be unrelated to this module; in my case it was because the wifi wasn't able to automatically reconnect after being down.

**Comment by dxfan227** [comment]
Thank u. Seems strange that it would only effect this module though no?

David Ruiz

**Comment by Gara64** [comment]
Any module that needs network is impacted by a connectivity failure, but each of them handle errors differently. In this case, I guess the error is actually returned by the Google maps API and displayed by the module.
