### ISSUE TITLE
white box where map should be

### ISSUE THREAD

**Issue by Jbebco3** [mrdis/MMM-google-route#21]
Hi, I configured the settings to my specifics but still cannot get the map to show on my mirror. All that is displayed is a white box.

my config is 
`{
module: "MMM-google-route",
position: "top_left",
config: {
	key: "google api-key", 
	directionsRequest:{
		origin: {"lat": 40.0583287, "lng": -75.0074246},
		destination: {"lat": 39.9487306, "lng": -75.1965791},
			height: "400px",
			width: "400px",
			}
		}
	},`

**Comment by sy8282** [comment]
same issue for me i get a error map cannot be displayed

**Comment by mrdis** [comment]
If you properly indent your configuration json, you'll see that the height and width fields are not where they are supposed to be
```
		{ 
			module: "MMM-google-route",
			position: "top_left", 
			config: { 
				key: "google api-key", 
				directionsRequest:{ 
					origin: {"lat": 40.0583287, "lng": -75.0074246}, 
					destination: {"lat": 39.9487306, "lng": -75.1965791}, 
					height: "400px", 
					width: "400px", 
				} 
			} 
		}
```
They are in the drectionRequest object, while they should be in the config object, as follows
```
		{ 
			module: "MMM-google-route",
			position: "top_left", 
			config: { 
				key: "google api-key", 
				directionsRequest:{ 
					origin: {"lat": 40.0583287, "lng": -75.0074246}, 
					destination: {"lat": 39.9487306, "lng": -75.1965791}, 
				},
				height: "400px", 
				width: "400px", 
			} 
		}
```
Just fix your configuration
