### ISSUE TITLE
refresh

### ISSUE THREAD

**Issue by sy8282** [mrdis/MMM-google-route#22]
hi the refresh settings have me all confused

would someone be able to tell me how to have this module only run from 6.00am to 7.00am monday to friday

i have the scheduler module but cant work out the timings etc

**Comment by mrdis** [comment]
The following schedule triggers a notification every 5 minutes from 6 to 7 AM from monday to friday:
`*/5 6 * * 1-5`
You can check it [here](https://crontab.guru/#*/5_6_*_*_1-5)
