### ISSUE TITLE
What formats to use for origin and destination?

### ISSUE THREAD

**Issue by fallenbuddhist** [mrdis/MMM-google-route#25]
I have tried place names (using latlng, places, etc.), but seems my formatting must be off. Does anyone have an example of a location format that is working for this? 

Formats That Do Not Seem To Work:
- '<lat: -34.397, lng: 150.644>'
- '<City+Hall%2C+New+York%2C+NY>'

**Comment by mrdis** [comment]
This example works:

>                 directionsRequest:{
> 					origin: '725 Piikoi St',
> 					destination: '2099 Houghtailing St'
>                 }

**Comment by fallenbuddhist** [comment]
No need for city or zip?

**Comment by mrdis** [comment]
You can add it if you think the addresses may be ambiguous.
There is not a strict specification of the format to use in the API docs, so I think that anything that gives you the correct result when  you put it in the google maps search bar should be fine :)
