### ISSUE TITLE
Display TRANSIT departure/arrival times

### ISSUE THREAD

**Issue by RoninActual** [mrdis/MMM-google-route#32]
Is it possible to use the clickableIcons map option or something similar to allow clicks on individual transit icons (such as a train in the example below) so departure and arrival times of the train are displayed?  Alternatively can the departure and arrival time be displayed alongside the route time and distance below the map?  Whatever is easiest.

Here is the code I am using:

>                 {
                        module: 'MMM-google-route',
                        position: 'top_right',
                        config: {
                                key: 'API Key',
                                title: 'Train Route',
                                mapOptions:{
                                disableDefaultUI: false,
                                keyboardShortcuts: false,
                                clickableIcons: true,
                                },
                                directionsRequest:{
                                origin: 'xx.xxxx, -xx.xxx',
                                destination: 'xx.xxx, -xx.xxx',
                                travelMode: 'TRANSIT',
                                transitOptions:{
                                modes: ["TRAIN"],
                                },
                                provideRouteAlternatives: true
                                },
                        showAge: false,
                        }
                },

![TRANSIT](https://user-images.githubusercontent.com/45614416/141486320-6919ba7d-3fad-487d-a4a9-d1245e462b0b.png)

**Comment by mrdis** [comment]
Hi, I added the departure time to the displayed information, when available!

**Comment by RoninActual** [comment]
This is great!  I have departure times now, they work perfectly.  Thank you for the quick fix!

![image](https://user-images.githubusercontent.com/45614416/141799435-917338d3-0eb9-4c65-a49c-cf3d19eeb429.png)
