### ISSUE TITLE
Is there a way to change the font size of the routes? And to sort it on time

### ISSUE THREAD

**Issue by NickBeugel** [mrdis/MMM-google-route#4]
I'd like to have the recommended routes text a little smaller, it doesn't scale with the map.
And is there a way to sort it on time? I get the slowest route before the quickest, I think it's sorted on distance seen as the slowest is the least distance driving.

Anyone has a sollution for this?

**Comment by mrdis** [comment]
Hi! I think I may come up with something to allow customization of the routes text style, I may work on it in the next days.
Regarding the sorting, the current order of the routes is the one returned by google, I think that the first entry is the "recommended" route, probably a tradeoff between duration and distance.

**Comment by NickBeugel** [comment]
Awesome! The sorting is not really an issue so no worries :)
Thanks dude!

**Comment by mrdis** [comment]
You should now be able to set the font size as a percentage of the original size! 
Just set the fontSize config param to e.g. "80%"
Enjoy :)
