### ISSUE TITLE
Module not refreshing once loaded

### ISSUE THREAD

**Issue by stanvv** [mrdis/MMM-google-route#7]
It seems the module is not refreshing once loaded:
- In the morning, when I know there's a traffic jam of about 10 minutes, it still displays a travel time of 30 minutes (which is the travel time without a traffic jam).
- When I check google maps on my phone, it says 40 minutes
- When I restart the mirror, it says 40 minutes
- When I check the mirror on a different device (e.g. my phone) it says 40 minutes
- Other modules (such as train departures) do show up-to-date information

I adjusted the refreshPeriod to 2, just to see if that causes the issue, but it does not seem to have any impact.

**Comment by stanvv** [comment]
I'm not sure how to check this, but when accessing the MagicMirror on my laptops browser and checking ctrl+shift+i I don't see any errors when I search for "route". Also, when checking the Network tab, my google route requests returns a status 200. 
Will try to have the page open on my laptop next to my mirror when there's a traffic jam to see whether it has to do with the display output generated from the raspberry pi.

**Comment by stanvv** [comment]
I tried to change a few small things in the config.js (e.g. moving the module from bottom left to bottom right) and restarted, seems to be working fine for last 2 days. Not sure what caused the issue last week. Will close the thread for now

**Comment by stanvv** [comment]
Unfortunately it happened again yesterday: it said 49 minutes (which means it didn't refresh) for at least 12 hours.

**Comment by mrdis** [comment]
Could it be due to google api usage [limits](https://developers.google.com/maps/documentation/directions/usage-and-billing#standard-usage-limits-and-billing)?
It should be 2500 requests per day on a free account, so if you have 2 modules on the mirror refreshing every minute it's already 2880 requests per day.
Plus if you check the mirror from other devices, more requests are performed.

You shold check the [google console](https://cloud.google.com/console/google/maps-apis/overview) and see how many requests you are performing.

**Comment by stanvv** [comment]
Since June this year the requests per day limits have ended. So if I go over the $200 free requests, it should just be billed to me. But I'm at 8,090 direction requests and 103 map requests last 30 days

**Comment by mrdis** [comment]
I just pushed some commits that show up any errors that may occur during the refreshing. 
I hope this will get us some insight on the issue.

**Comment by stanvv** [comment]
Thanks, just pulled the changes and restarted MM. What's the best way to troubleshoot? Keep the MM open  in a browser for a couple of hours and should the errors appear at the Console tab of Chrome inspect (ctrl + shift + i) for example?

**Comment by mrdis** [comment]
If the call to the google API returns an error or if an exception occurs during the periodic refresh, they will be shown instead of the routes, so you will see them directly on the mirror.

**Comment by stanvv** [comment]
Ah okay clear. So, like I said in the previous post: something else is going wrong now, I do not see the module at all anymore on my mirror. (or when connected through VNC). When I connect with my laptop within the home network it does show up correctly. See attached (I disabled all the other modules for privacy reason): on the left while connected with my laptop, on the right when connected via VNC.
![laptop_vs_vnc](https://user-images.githubusercontent.com/38349246/50516320-724edd80-0aaa-11e9-9fd5-09e9133502f7.PNG)

**Comment by stanvv** [comment]
Ah okay clear. So, like I said in the previous post: something else is going wrong now, I do not see the module at all anymore on my mirror. (or when connected through VNC). When I connect with my laptop within the home network it does show up correctly. See attached: on the left while connected with my laptop, on the right when connected via VNC  (I disabled all the other modules and faded out the route for privacy reason)
![laptop_vs_vnc_1](https://user-images.githubusercontent.com/38349246/50516416-00c35f00-0aab-11e9-8ac9-87d3cf865ac1.png)

**Comment by mrdis** [comment]
I discovered that I introduced a syntax error when running under electron.. I just fixed that, so the module should be back now.

**Comment by stanvv** [comment]
Thanks, it is visible once again! Will check if I see errors on my mirror when it fails to update in the coming days.

**Comment by stanvv** [comment]
So this morning I had the error "OVER_QUERY_LIMIT". Not sure what exactly was causing is since the refreshPeriod was set at 5, but I changed it to 8 and also created a new key for 2 other projects (for which I was using the same API key, but they were not really active last couple of weeks). Will check what happens next days.

**Comment by stanvv** [comment]
So far I've had one more OVER_QUERY_LIMIT and one UNKNOWN_ERROR. So the issue does not have to do with the functionality of the module, hence will close this. Thanks for helping out!
