### ISSUE TITLE
Don't get it running

### ISSUE THREAD

**Issue by rosenmak** [mrdis/MMM-google-route#9]
I don't get it running.
I took the directions API and added this to config:

{
			module: "MMM-google-route",
			position: "bottom_left",
			config: {
				key: "AIzaSyxxxxxxxxxxxx1cIAbkqwSw",
				directionsRequest: {
					origin:		{
						lat: 49.2442299,
						lng: 16.3287461
						},
					destination: 	{
						lat: 46.542438, 
						lng: 15.5678409
						},
					}
			}
		},

I'm no programmer so I would be thankful for any help!
THX

**Comment by mrdis** [comment]
I tried your directionsRequest configuration, and it works fine, so the problem must be elsewhere.
What issue are you experiencing exactly?

**Comment by rosenmak** [comment]
The part of the screen where the MMM-google-routes should be is black. I don't get an error. All other modules are working.

I now activated all kinds APIs which are available from google: direction, distance matrix, geocoding,... but it doesn't work.
I changed the key, copied it into the config.js and checked it again.
Nothing works.

I recognized that in my google account no activities happend. There are no request or errors shown at the APIs.
I only have the "free" account. I subscribed with my credit card, but google always wants me to upgrade my account. Could it be a problem with google?

**Comment by mrdis** [comment]
Ok, I just fixed an issue that may have been the cause for that behaviour, it should be working now.

**Comment by Photroncis** [comment]
I just installed it and am getting the same error, the "Oops! Something went wrong. This page didn’t load Google Maps correctly. See the JavaScript console for technical details."

**Comment by mrdis** [comment]
If you have a mouse and a keyboard connected to the pi you should be able to open the javascript console by pressing alt to show the menu, then clicking on "view" and then "toggle developer tools".
Then in the console tab you will see the log.

**Comment by rosenmak** [comment]
Google Maps Javascript API
error: RefererNotAllowedMapError
Your site URL to be authorized: http://localhost:8080/

I tried to add http://localhost:8080/ to my google account but it says that this is no URL.

**Comment by mrdis** [comment]
It seems like you have configured a referer based usage restriction on your API key.
Personally, I configured the key to be without restrictions and I'm not sure on how to configure a referer restriction. So if it is viable for you, I would advice to use a key without restrictions.

**Comment by Photroncis** [comment]
That fixed it for me(taking off the restrictions), thank you so much!

**Comment by rosenmak** [comment]
Now it works!
I needed to enable Maps Javascript API and turn off the restrictions.

THX alot.
